let mongoose=require("mongoose")
let schema=mongoose.Schema({
    student1:{
        name:{
            type:String,
            default:null
        },
        rollno:{
            type:Number,
            default:0
    },
        filepath:{
            type:String,
            default:null
        }
    },
    student2:{
        name:{
            type:String,
            default:null
        },
        rollno:{
            type:Number,
            default:0
    },
    filepath:{
        type:String,
        default:null
    }
    }
    ,student3:{
        name:{
            type:String,
            default:null
        },
        rollno:{
            type:Number,
            default:0
    },
    filepath:{
        type:String,
        default:null
    }
}
    ,
    roomno:{
        type:Number,
        default:0
    },
    count:{
        type:Number,
        max:3,
        default:0
    }
    ,
    full:{
        type:Boolean,
        default:false
    }

})
module.exports=mongoose.model("updatedroomdata5",schema);